---
Logging:
  LogLevel:
    Default: Warning
AllowedHosts: "*"

UseCfConnectors: 'yes' - from git
AvailableConnectorsCount: 1
CfConnector:
  Type: azuresql
  Uri: http://blah-blah/
  Target: randomvalue
  
info:
description: Rams Spring Cloud Samples
url: https://github.com/kolluri-rk/config-repo
